name: Haskell CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: 'Cache .stack'
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-
    - run: stack build
    - name: 'Set up HLint'
      uses: rwe/actions-hlint-setup@v1.0.2
    - name: 'Run HLint'
      uses: rwe/actions-hlint-run@v2.0.1
      with:
        path: '["src/"]'
        fail-on: warning